physical_constants: 
  speed_of_light: 1
  gravitational_constant: 1

spacetime_parameters:
  mass: 
    in_meters: 500
  charge: 0
  angular_momentum: 0

coordinate_domains:
  - dimension: "time"
    start: 0
    stop: 10
    step: 0.1
  - dimension: "reduced circumference" # as factors of M
    start: 2
    stop: 100
    step: 0.1