physical_constants: 
  speed_of_light: 1
  gravitational_constant: 1

spacetime_parameters:
  mass: 
    in_meters: 500
  charge: 0
  angular_momentum: 0

coordinate_domains:
  - dimension: "reduced circumference"
    start: 1001
    stop: 500000
    step: 0.01
  - dimension: "time"
    start: 0
    stop: 10
    step: 0.001
